import sample from "../../assets/sample.png";
import Bitmap from "../../assets/Bitmap.png";
const data = [
  {
    id: 1,
    name: "Test Whatsapp",
    region: "US",
    createdOn: 1559807714999,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: Bitmap,
  },
  {
    id: 2,
    name: "Super Jewels Quest",
    region: "CA, FR",
    createdOn: 1559806715124,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: Bitmap,
  },
  {
    id: 3,
    name: "Mole Slayer",
    region: "FR",
    createdOn: 1559806711124,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: Bitmap,
  },
  {
    id: 4,
    name: "Mancala Mix 1",
    region: "JP",
    createdOn: 1600046719886,
    price: "Price info of Mancala Mix 1",
    csv: "Some CSV link for Mancala Mix 1",
    report: "Some report link for Mancala Mix 1",
    image_url: sample,
  },
  {
    id: 5,
    name: "Test Whatsapp",
    region: "US",
    createdOn: 1600942760201,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: sample,
  },
  {
    id: 6,
    name: "Super Jewels Quest",
    region: "CA, FR",
    createdOn: 1600942760201,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: sample,
  },
  {
    id: 7,
    name: "Mole Slayer",
    region: "FR",
    createdOn: 1600942760201,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: Bitmap,
  },
  {
    id: 8,
    name: "Mancala Mix",
    region: "JP",
    createdOn: 1600942760201,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: Bitmap,
  },
  {
    id: 8,
    name: "Mancala Mix 1",
    region: "JP",
    createdOn: 1600942760201,
    price: "Price info of Mancala Mix 1",
    csv: "Some CSV link for Mancala Mix 1",
    report: "Some report link for Mancala Mix 1",
    image_url: Bitmap,
  },
  {
    id: 9,
    name: "Mancala Mix 2",
    region: "JP",
    createdOn: 1600942760201,
    price: "Price info of Mancala Mix 2",
    csv: "Some CSV link for Mancala Mix 2",
    report: "Some report link for Mancala Mix 2",
    image_url: Bitmap,
  },
  {
    id: 10,
    name: "Test Whatsapp",
    region: "US",
    createdOn: 1601940540697,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: Bitmap,
  },
  {
    id: 11,
    name: "Super Jewels Quest",
    region: "CA, FR",
    createdOn: 1601940540696,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: Bitmap,
  },
  {
    id: 12,
    name: "Mole Slayer",
    region: "FR",
    createdOn: 1601940540695,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: Bitmap,
  },
  {
    id: 13,
    name: "Mancala Mix",
    region: "JP",
    createdOn: 1601940540634,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: Bitmap,
  },
  {
    id: 14,
    name: "Mancala Mix 3",
    region: "JP",
    createdOn: 1601990570633,
    price: "Price info of Mancala Mix 3",
    csv: "Some CSV link for Mancala Mix 3",
    report: "Some report link for Mancala Mix 1",
    image_url: Bitmap,
  },
];
export default data;
